[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=15768000"
